openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    email: support@zegocloud.com

servers:
  - url: https://zim-api.zego.im
    description: ZIM 服务端 API 地址

tags:
  - name: Group
    description: 群组管理相关接口

paths:
  /:
    get:
      tags:
        - Group
      summary: 解散群组
      description: |
        解散群组

        <Note title="调用频率限制">1  次/秒。</Note>

      operationId: disband-a-group-chat
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im?Action=DismissGroup
          schema:
            type: string
            enum: ["DismissGroup"]
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'

      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisbandAGroupChatResponse'

components:
  schemas:
    DisbandAGroupChatResponse:
      allOf:
        - $ref: '../shared-components.yaml#/components/schemas/StandardResponse'
