openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - name: User
    description: 用户管理相关接口

paths:
  /:
    post:
      tags:
        - User
      summary: 批量添加好友
      description: |
        调用此接口，可为用户直接批量添加至多 20 名好友，无需对方同意。如需上调（最多可为 50），请联系 ZEGO 技术支持。

        每名用户最多可以拥有 3000 名好友。

        为用户添加好友成功后，相关用户的客户端将通过以下 ZIM SDK 的回调接口接收好友列表更新的通知：

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        | --- | --- | --- | --- |
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-friend-list-changed-friend-info-list) | [onFriendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-friend-list-changed-friend-info-list) | [onFriendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-friend-list-changed) |

        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        | --- | --- | --- | --- |
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#friend-list-changed) |  [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#friend-list-changed) | [onFriendListChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onFriendListChanged.html) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#friend-list-changed)   |

        |uni-app \| uni-app x-25% | HarmonyOS-25% |
        |  --- | --- |
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#friend-list-changed) |

        <Note title="调用频率限制">20 次/秒。</Note>

        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 [调用方式 - 公共请求参数](../Accessing%20Server%20APIs.mdx#2-公共参数)。

        <Note title="说明">
        以下 `FromUserId` 和 `UserId` 对应的用户已在客户端调用 `login` 方法登录 ZIM 服务，或已调用 [服务端 API](./Batch%20register%20users.mdx) 完成注册。
        </Note>
      operationId: batch-add-friends
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im?Action=AddFriends
          schema:
            type: string
            enum: ["AddFriends"]
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchAddFriendsRequest'
            example:
              FromUserId: "zego_user"
              FriendInfos:
                - UserId: "usera1"
                  Wording: "Wording1"
                  FriendAlias: "alias1"
                  Attributes:
                    - Key: "k1"
                      Value: "Value"
                    - Key: "k2"
                      Value: "Value1"
                - UserId: "usera2"
                  Wording: "Wording2"
                  FriendAlias: "alias2"
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchAddFriendsResponse'
              example:
                Code: 0
                Message: "success"
                RequestId: "343649807833778782"
                ErrorList:
                  - UserId: "usera2"
                    SubCode: 660000012
                    SubMessage: "user already exists"

components:
  schemas:
    BatchAddFriendsRequest:
      type: object
      required:
        - FromUserId
        - FriendInfos
      properties:
        FromUserId:
          type: string
          description: 为此 UserId 添加好友。
          example: "zego_user"
        FriendInfos:
          type: array
          description: 好友结构体对象。默认上限为 20。
          maxItems: 20
          items:
            type: object
            required:
              - UserId
            properties:
              UserId:
                type: string
                description: 目标用户 ID。长度上限为 32 字节。
                maxLength: 32
                example: "usera1"
              Wording:
                type: string
                description: FromUserId 对目标用户成为好友时的附言，长度上限为 256 字符。
                maxLength: 256
                example: "Wording1"
              FriendAlias:
                type: string
                description: FromUserId 对目标用户的备注，长度上限为 256 字符。
                maxLength: 256
                example: "alias1"
              FriendTime:
                type: integer
                format: int64
                description: |
                  成为好友的时间。此参数可在数据迁移时用于导入好友列表。
                  - 为 0 时，ZIM 服务端以当前时间为准。
                  - 不为 0 时，此参数需为 MS 时间戳，且不晚于当前时间。
                example: 0
              Attributes:
                type: array
                description: 好友属性，上限 5 个。
                maxItems: 5
                items:
                  type: object
                  required:
                    - Key
                    - Value
                  properties:
                    Key:
                      type: string
                      description: 好友属性的键。取值仅能为 k0、k1、k2、k3、k4。
                      enum: ["k0", "k1", "k2", "k3", "k4"]
                      example: "k1"
                    Value:
                      type: string
                      description: 好友属性的值。
                      example: "Value"

    BatchAddFriendsResponse:
      allOf:
        - $ref: '../shared-components.yaml#/components/schemas/StandardResponse'
        - type: object
          properties:
            ErrorList:
              type: array
              description: 失败信息列表。
              items:
                $ref: '../shared-components.yaml#/components/schemas/ErrorInfo'
