openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    email: support@zegocloud.com

servers:
  - url: https://zim-api.zego.im
    description: ZIM 服务端 API 地址

tags:
  - name: User
    description: 用户管理相关接口

paths:
  /:
    get:
      tags:
        - User
      summary: 删除所有好友
      description: |
        调用此接口，可为用户单向或双向删除全部好友数据。

        以用户 A、B 举例说明单向删除和双向删除：
        - 单向删除：当用户 A 单向删除了用户 B，用户 B 不再是用户 A 的好友、用户 A 仍为用户 B 的好友。
        - 双向删除：当用户 A 双向删除了用户 B，彼此都不再是对方的好友。

        为用户删除好友成功后，相关用户的客户端将通过 ZIM SDK 的回调接口接收好友列表更新的通知。

        <Note title="调用频率限制">20 次/秒。</Note>

        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 [调用方式 - 公共请求参数](../accessing-server-apis.mdx#2-公共参数)。

        <Note title="说明">
        FromUserId 仅支持数字，英文字符和 {"'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', '{', '}', '|', '~'}。
        </Note>
      operationId: delete-all-friends
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im?Action=DeleteAllFriends
          schema:
            type: string
            enum: ["DeleteAllFriends"]
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: FromUserId
          in: query
          required: true
          description: 为此 UserId（已在客户端调用 `login` 方法登录 ZIM 服务，或已调用服务端 API 完成注册）删除全部好友。
          schema:
            type: string
            maxLength: 32
            example: "zego_user"
        - name: DeleteType
          in: query
          required: true
          description: |
            删除类型：
            - 0：双向删除
            - 1：单向删除
          schema:
            type: integer
            enum: [0, 1]
            example: 1
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAllFriendsResponse'

components:
  schemas:
    DeleteAllFriendsResponse:
      allOf:
        - $ref: '../shared-components.yaml#/components/schemas/StandardResponse'
