openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - name: User
    description: 用户管理相关接口

paths:
  /:
    get:
      tags:
        - User
      summary: 查询用户在线状态
      description: |
        查询用户的在线状态，支持查询单个用户、或批量查询多个用户的在线状态。
        
        调用频率限制：20 次/秒。
      operationId: query-users-online-status
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im?Action=QueryUserOnlineState
          schema:
            type: string
            enum: ["QueryUserOnlineState"]
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: UserId
          in: query
          required: true
          description: 需要查询的用户 ID 列表，最大支持查询 100 个用户 ID。示例：UserId[]=a&UserId[]=b
          style: form
          explode: true
          schema:
            type: array
            maxItems: 100
            items:
              type: string
              example: "user123"
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryUserOnlineStatusResponse'
              example:
                Code: 0
                Message: "success"
                RequestId: "343649807833778782"
                Result:
                  - UserId: "id1"
                    Status: "Offline"
                  - UserId: "id2"
                    Status: "Online"
                ErrorList:
                  - UserId: "id4"
                    SubCode: 660200001

components:
  schemas:
    QueryUserOnlineStatusResponse:
      allOf:
        - $ref: '../shared-components.yaml#/components/schemas/StandardResponse'
        - type: object
          properties:
            Result:
              type: array
              description: 查询的用户状态结果。用户处于在线状态或离线状态时，通过该字段返回。
              items:
                type: object
                properties:
                  UserId:
                    type: string
                    description: 在线或离线用户的 ID。
                    example: "id1"
                  Status:
                    type: string
                    description: 用户状态
                    enum: ["Online", "Offline"]
                    example: "Offline"
            ErrorList:
              type: array
              description: |
                查询失败列表。用户 ID 不存在或者用户已登出时，通过该字段返回。
                - Code 为 0：
                  - ErrorList 为空，全部用户在线状态查询成功。
                  - ErrorList 不为空，表示部分用户在线状态查询失败，请参考 SubCode 处理。
                - Code 不为 0：
                  - ErrorList 为空，表示参数错误、接口频率限制、系统错误。
                  - ErrorList 不为空，表示所有用户在线状态查询失败。
              items:
                type: object
                properties:
                  UserId:
                    type: string
                    description: 不存在的用户 ID 或已登出用户的 ID。
                    example: "id4"
                  SubCode:
                    type: integer
                    description: 查询失败时的返回码。
                    example: 660200001
