openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    email: support@zegocloud.com

servers:
  - url: https://zim-api.zego.im
    description: ZIM 服务端 API 地址

tags:
  - name: Room
    description: 房间管理相关接口

paths:
  /:
    get:
      tags:
        - Room
      summary: KickoutRoomUser
      description: |
        移除房间内的指定用户。多用于内容审核场景下，开发者后台发现某个用户违规时，可通过本接口将该用户移出房间。

        客户端将通过 ZIM SDK 的以下回调接口，接收用户被移除、房间内用户变更等通知。
        
        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [roomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-room-state-changed-event-extended-data) | [onRoomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-room-state-changed) | [roomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-room-state-changed-event-extended-data) | [onRoomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-room-state-changed) |
        
        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% | 
        |-----|---------|---------|---------|
        | [roomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#room-state-changed) | [roomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#room-state-changed) | [onRoomStateChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onRoomStateChanged.html) | [groupMemberStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-member-state-changed) |
        
        | Unity3D-25% | uni-app \| uni-app x-25% |  HarmonyOS-25% | 
        |---------|--------------|-----------|
        | [OnRoomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-room-state-changed) |[groupMemberStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-member-state-changed) |[roomStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#room-state-changed) | |
        
        <Note title="调用频率限制">20  次/秒。</Note>
        <Note title="说明">
        RoomId、UserId[] 仅支持数字，英文字符和 {"'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'"}。
        </Note>
      operationId: remove-user-from-the-room
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im?Action=KickoutRoomUser
          schema:
            type: string
            enum: ["KickoutRoomUser"]
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: RoomId
          in: query
          required: true
          description: 房间 ID。
          schema:
            type: string
        - name: UserId[]
          in: query
          required: true
          description: |
            需要移除的用户 ID 列表（已在客户端调用 'login' 方法登录 ZIM 服务，或已调用 [服务端 API](./../user/batch-register-users.mdx) 完成注册）），最大支持 50 个用户 ID。

            示例：UserId[]=a&UserId[]=b
          schema:
            type: array
            items:
              type: string
            maxItems: 50
        - name: CustomReason
          in: query
          required: false
          description: 移除用户的原因，建议最大不超过 32 字节。
          schema:
            type: string
            maxLength: 32

      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveUserFromTheRoomResponse'
components:
  schemas:
    RemoveUserFromTheRoomRequest:
      type: object
      required:
        - RoomId
        - UserId[]
      properties:
        RoomId:
          type: string
          description: 房间 ID。
        UserId[]:
          type: array
          description: |
            需要移除的用户 ID 列表（已在客户端调用 'login' 方法登录 ZIM 服务，或已调用 [服务端 API](./../user/batch-register-users.mdx) 完成注册）），最大支持 50 个用户 ID。

            示例：UserId[]=a&UserId[]=b
          items:
            type: string
          maxItems: 50
        CustomReason:
          type: string
          description: 移除用户的原因，建议最大不超过 32 字节。
          maxLength: 32

    RemoveUserFromTheRoomResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。
            
            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](./../return-codes.mdx)。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            </tr>
            <tr>
            <td>660000011</td>
            <td>用户个数超过限制。</td>
            </tr>
            <tr>
            <td>660300001</td>
            <td>房间不存在。</td>
            </tr>
            <tr>
            <td>660300002</td>
            <td>用户不在此房间内。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
